### ISSUE TITLE
Ability to configure weld settings via MP Config

### ISSUE THREAD

**Issue by johnament** [hammock-project/hammock#113]
Weld exposes a number of properties to set via SE containers:

```java
    public static final String ARCHIVE_ISOLATION_SYSTEM_PROPERTY = "org.jboss.weld.se.archive.isolation";
    public static final String DEV_MODE_SYSTEM_PROPERTY = "org.jboss.weld.development";
    public static final String SHUTDOWN_HOOK_SYSTEM_PROPERTY = "org.jboss.weld.se.shutdownHook";
    public static final String JAVAX_ENTERPRISE_INJECT_SCAN_IMPLICIT = "javax.enterprise.inject.scan.implicit";
```

We should set these when creating the Weld container (since weld doesn't have any MP Config support OOTB).  They should be set by default to:

- `false`
- `false`
- `true`
- `false`

And allow a user to override via any MP Config Source.

**Comment by johnament** [comment]
@derekm not sure if you've seen something similar to run my app, on Hammock 2.0, I had to add `-Dorg.jboss.weld.se.archive.isolation=false` to the command line.  Then it ran fine.  I don't think I saw this when I first released 2.0, but it's possible that I missed this issue.  Have you seen something similar?

**Comment by derekm** [comment]
I tried porting to both `rest-cxf` & `dist-microprofile` today. `dist-microprofile` worked best, but it couldn't find my JAX-RS endpoints. Is that a symptom?

**Comment by johnament** [comment]
@derekm that is a symptom.  can you retry on 2.1-SNAPSHOT?
