### ISSUE TITLE
Automatic propagation of jersey properties

### ISSUE THREAD

**Issue by johnament** [hammock-project/hammock#118]
Most jersey properties are prefixed with `jersey`.  Hammock should automatically propagate these properties into the jersey servlet that is registered to make it easier to integrate.

**Comment by derekm** [comment]
This would be really handy for `jersey.config.server.provider.classnames`, `jersey.config.server.provider.packages` and other settings.

Should this issue be part of the 2.1 milestone?

I could see several modules wanting to provide their own classes and packages, which would require that the configs be merged. Then there's the question of being Jersey-specific (works with `rest-jersey` only) or Hammock-specific (works with `rest-*`).

**Comment by johnament** [comment]
I'm planning to just load any MP Config properties named `jersey.*` and feeding them into the jersey runtime.  That seems to cover all use cases.

Yes, I'm going to plan to do this in 2.1, I believe its just a matter of using `ConfigLoader.loadAllProperties("jersey",false);` and registering those as init params.

Patches always welcome :-)
