### ISSUE TITLE
Simple example not work with Hammock 2.0

### ISSUE THREAD

**Issue by yblazart** [hammock-project/hammock#124]
Hello.

Following tutorial https://hammock-project.github.io/guides/gettingstarted.html, and adding an empty beans.xml, I'm facing a problem while running ws.ament.hammock.Bootstrap.

The Hello JaxRS endpoint is not mounted.
In fact there is a stack trace where I can see : 

> at org.apache.cxf.cdi.JAXRSCdiResourceExtension.load

Everything because of this : 

> 18:52:33.184 [main] INFO  org.atmosphere.cpr.AtmosphereFramework - Installed WebSocketProtocol org.atmosphere.websocket.protocol.SimpleHttpProtocol 
> 18:52:33.189 [main] WARN  org.atmosphere.cpr.DefaultAsyncSupportResolver - Failed to create AsyncSupport class: class org.atmosphere.container.JSR356AsyncSupport, error: java.lang.reflect.InvocationTargetException
> 18:52:33.189 [main] ERROR org.atmosphere.cpr.DefaultAsyncSupportResolver - Real error: Unable to configure jsr356 at that stage. ServerContainer is null
> java.lang.IllegalStateException: Unable to configure jsr356 at that stage. ServerContainer is null

Any ideas about that ?

Full logs : 

> 
> /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java "-javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=55823:/Applications/IntelliJ IDEA.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/lib/tools.jar:/Users/yblazart/Dev/sources/sandbox/test-hammock-001/target/classes:/Users/yblazart/.m2/repository/ws/ament/hammock/dist-microprofile/2.0/dist-microprofile-2.0.jar:/Users/yblazart/.m2/repository/ws/ament/hammock/bootstrap-weld3/2.0/bootstrap-weld3-2.0.jar:/Users/yblazart/.m2/repository/org/jboss/logging/jboss-logging/3.3.1.Final/jboss-logging-3.3.1.Final.jar:/Users/yblazart/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar:/Users/yblazart/.m2/repository/javax/enterprise/cdi-api/2.0/cdi-api-2.0.jar:/Users/yblazart/.m2/repository/javax/el/javax.el-api/3.0.0/javax.el-api-3.0.0.jar:/Users/yblazart/.m2/repository/javax/interceptor/javax.interceptor-api/1.2/javax.interceptor-api-1.2.jar:/Users/yblazart/.m2/repository/org/jboss/weld/se/weld-se-core/3.0.1.Final/weld-se-core-3.0.1.Final.jar:/Users/yblazart/.m2/repository/org/jboss/weld/environment/weld-environment-common/3.0.1.Final/weld-environment-common-3.0.1.Final.jar:/Users/yblazart/.m2/repository/org/jboss/weld/weld-core-impl/3.0.1.Final/weld-core-impl-3.0.1.Final.jar:/Users/yblazart/.m2/repository/org/jboss/spec/javax/interceptor/jboss-interceptors-api_1.2_spec/1.0.0.Final/jboss-interceptors-api_1.2_spec-1.0.0.Final.jar:/Users/yblazart/.m2/repository/org/jboss/weld/probe/weld-probe-core/3.0.1.Final/weld-probe-core-3.0.1.Final.jar:/Users/yblazart/.m2/repository/org/jboss/classfilewriter/jboss-classfilewriter/1.2.1.Final/jboss-classfilewriter-1.2.1.Final.jar:/Users/yblazart/.m2/repository/org/jboss/weld/servlet/weld-servlet-core/3.0.1.Final/weld-servlet-core-3.0.1.Final.jar:/Users/yblazart/.m2/repository/org/jboss/weld/weld-spi/3.0.SP1/weld-spi-3.0.SP1.jar:/Users/yblazart/.m2/repository/org/jboss/weld/weld-api/3.0.SP1/weld-api-3.0.SP1.jar:/Users/yblazart/.m2/repository/org/jboss/weld/module/weld-jsf/3.0.1.Final/weld-jsf-3.0.1.Final.jar:/Users/yblazart/.m2/repository/org/jboss/weld/module/weld-web/3.0.1.Final/weld-web-3.0.1.Final.jar:/Users/yblazart/.m2/repository/org/jboss/spec/javax/el/jboss-el-api_3.0_spec/1.0.7.Final/jboss-el-api_3.0_spec-1.0.7.Final.jar:/Users/yblazart/.m2/repository/ws/ament/hammock/rest-cxf/2.0/rest-cxf-2.0.jar:/Users/yblazart/.m2/repository/org/apache/cxf/cxf-integration-cdi/3.2.0/cxf-integration-cdi-3.2.0.jar:/Users/yblazart/.m2/repository/org/apache/cxf/cxf-core/3.2.0/cxf-core-3.2.0.jar:/Users/yblazart/.m2/repository/com/fasterxml/woodstox/woodstox-core/5.0.3/woodstox-core-5.0.3.jar:/Users/yblazart/.m2/repository/org/codehaus/woodstox/stax2-api/3.1.4/stax2-api-3.1.4.jar:/Users/yblazart/.m2/repository/org/apache/ws/xmlschema/xmlschema-core/2.2.2/xmlschema-core-2.2.2.jar:/Users/yblazart/.m2/repository/org/apache/cxf/cxf-rt-frontend-jaxrs/3.2.0/cxf-rt-frontend-jaxrs-3.2.0.jar:/Users/yblazart/.m2/repository/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.jar:/Users/yblazart/.m2/repository/org/apache/cxf/cxf-rt-rs-client/3.2.0/cxf-rt-rs-client-3.2.0.jar:/Users/yblazart/.m2/repository/org/apache/cxf/cxf-rt-rs-sse/3.2.0/cxf-rt-rs-sse-3.2.0.jar:/Users/yblazart/.m2/repository/org/atmosphere/atmosphere-runtime/2.4.14/atmosphere-runtime-2.4.14.jar:/Users/yblazart/.m2/repository/org/apache/cxf/cxf-rt-transports-http/3.2.0/cxf-rt-transports-http-3.2.0.jar:/Users/yblazart/.m2/repository/ws/ament/hammock/web-spi/2.0/web-spi-2.0.jar:/Users/yblazart/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar:/Users/yblazart/.m2/repository/javax/annotation/javax.annotation-api/1.3/javax.annotation-api-1.3.jar:/Users/yblazart/.m2/repository/ws/ament/hammock/web-undertow/2.0/web-undertow-2.0.jar:/Users/yblazart/.m2/repository/io/undertow/undertow-servlet/1.4.20.Final/undertow-servlet-1.4.20.Final.jar:/Users/yblazart/.m2/repository/io/undertow/undertow-core/1.4.20.Final/undertow-core-1.4.20.Final.jar:/Users/yblazart/.m2/repository/org/jboss/xnio/xnio-api/3.3.8.Final/xnio-api-3.3.8.Final.jar:/Users/yblazart/.m2/repository/org/jboss/xnio/xnio-nio/3.3.8.Final/xnio-nio-3.3.8.Final.jar:/Users/yblazart/.m2/repository/org/jboss/spec/javax/servlet/jboss-servlet-api_3.1_spec/1.0.0.Final/jboss-servlet-api_3.1_spec-1.0.0.Final.jar:/Users/yblazart/.m2/repository/org/jboss/spec/javax/annotation/jboss-annotations-api_1.2_spec/1.0.0.Final/jboss-annotations-api_1.2_spec-1.0.0.Final.jar:/Users/yblazart/.m2/repository/io/undertow/undertow-websockets-jsr/1.4.20.Final/undertow-websockets-jsr-1.4.20.Final.jar:/Users/yblazart/.m2/repository/org/jboss/spec/javax/websocket/jboss-websocket-api_1.1_spec/1.1.0.Final/jboss-websocket-api_1.1_spec-1.1.0.Final.jar:/Users/yblazart/.m2/repository/ws/ament/hammock/hammock-core/2.0/hammock-core-2.0.jar:/Users/yblazart/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:/Users/yblazart/.m2/repository/org/eclipse/microprofile/config/microprofile-config-api/1.1/microprofile-config-api-1.1.jar:/Users/yblazart/.m2/repository/org/osgi/org.osgi.annotation.versioning/1.0.0/org.osgi.annotation.versioning-1.0.0.jar:/Users/yblazart/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.9.0/log4j-slf4j-impl-2.9.0.jar:/Users/yblazart/.m2/repository/org/apache/logging/log4j/log4j-api/2.9.0/log4j-api-2.9.0.jar:/Users/yblazart/.m2/repository/org/apache/logging/log4j/log4j-core/2.9.0/log4j-core-2.9.0.jar:/Users/yblazart/.m2/repository/org/apache/logging/log4j/log4j-jul/2.9.0/log4j-jul-2.9.0.jar:/Users/yblazart/.m2/repository/ws/ament/hammock/johnzon/2.0/johnzon-2.0.jar:/Users/yblazart/.m2/repository/org/apache/johnzon/johnzon-jaxrs/1.1.3/johnzon-jaxrs-1.1.3.jar:/Users/yblazart/.m2/repository/org/apache/johnzon/johnzon-mapper/1.1.3/johnzon-mapper-1.1.3.jar:/Users/yblazart/.m2/repository/org/apache/johnzon/johnzon-core/1.1.3/johnzon-core-1.1.3.jar:/Users/yblazart/.m2/repository/org/apache/johnzon/johnzon-jsonb/1.1.3/johnzon-jsonb-1.1.3.jar:/Users/yblazart/.m2/repository/org/apache/geronimo/specs/geronimo-json_1.1_spec/1.0/geronimo-json_1.1_spec-1.0.jar:/Users/yblazart/.m2/repository/org/apache/geronimo/specs/geronimo-jsonb_1.0_spec/1.0/geronimo-jsonb_1.0_spec-1.0.jar:/Users/yblazart/.m2/repository/ws/ament/hammock/util-health/2.0/util-health-2.0.jar:/Users/yblazart/.m2/repository/org/eclipse/microprofile/health/microprofile-health-api/1.0/microprofile-health-api-1.0.jar:/Users/yblazart/.m2/repository/org/apache/geronimo/config/geronimo-config-impl/1.0/geronimo-config-impl-1.0.jar:/Users/yblazart/.m2/repository/ws/ament/hammock/security-jose/2.0/security-jose-2.0.jar:/Users/yblazart/.m2/repository/com/nimbusds/nimbus-jose-jwt/5.1/nimbus-jose-jwt-5.1.jar:/Users/yblazart/.m2/repository/com/github/stephenc/jcip/jcip-annotations/1.0-1/jcip-annotations-1.0-1.jar:/Users/yblazart/.m2/repository/net/minidev/json-smart/2.3/json-smart-2.3.jar:/Users/yblazart/.m2/repository/net/minidev/accessors-smart/1.2/accessors-smart-1.2.jar:/Users/yblazart/.m2/repository/org/ow2/asm/asm/5.0.4/asm-5.0.4.jar:/Users/yblazart/.m2/repository/ws/ament/hammock/security-spi/2.0/security-spi-2.0.jar:/Users/yblazart/.m2/repository/org/eclipse/microprofile/jwt/microprofile-jwt-auth-api/1.0/microprofile-jwt-auth-api-1.0.jar ws.ament.hammock.Bootstrap
> objc[14412]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java (0x1069764c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x1089bc4e0). One of the two will be used. Which one is undefined.
> janv. 30, 2018 6:52:29 PM org.apache.geronimo.config.configsource.PropertyFileConfigSourceProvider <init>
> INFOS: Custom config found by GeronimoConfig. Name: 'META-INF/microprofile-config.properties', URL: 'jar:file:/Users/yblazart/.m2/repository/ws/ament/hammock/util-health/2.0/util-health-2.0.jar!/META-INF/microprofile-config.properties'
> janv. 30, 2018 6:52:29 PM org.apache.geronimo.config.configsource.PropertyFileConfigSourceProvider <init>
> INFOS: Custom config found by GeronimoConfig. Name: 'META-INF/microprofile-config.properties', URL: 'jar:file:/Users/yblazart/.m2/repository/ws/ament/hammock/security-jose/2.0/security-jose-2.0.jar!/META-INF/microprofile-config.properties'
> 18:52:29.805 [main] INFO  org.jboss.weld.Version - WELD-000900: 3.0.1 (Final)
> 18:52:30.078 [main] INFO  org.jboss.weld.Bootstrap - WELD-ENV-000014: Falling back to Java Reflection for bean-discovery-mode="annotated" discovery. Add org.jboss:jandex to the classpath to speed-up startup.
> 18:52:30.190 [main] INFO  org.jboss.weld.Bootstrap - WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
> 18:52:30.743 [ForkJoinPool.commonPool-worker-7] WARN  org.jboss.weld.Validator - WELD-001473: javax.enterprise.inject.spi.Bean implementation org.apache.cxf.cdi.CdiBusBean@2b76ff4e declared a normal scope but does not implement javax.enterprise.inject.spi.PassivationCapable. It won't be possible to inject this bean into a bean with a passivating scope (@SessionScoped, @ConversationScoped). This can be fixed by assigning the Bean implementation a unique id by implementing the PassivationCapable interface.
> 18:52:30.746 [ForkJoinPool.commonPool-worker-5] WARN  org.jboss.weld.Validator - WELD-001473: javax.enterprise.inject.spi.Bean implementation org.apache.cxf.cdi.DefaultApplicationBean@524f3b3a declared a normal scope but does not implement javax.enterprise.inject.spi.PassivationCapable. It won't be possible to inject this bean into a bean with a passivating scope (@SessionScoped, @ConversationScoped). This can be fixed by assigning the Bean implementation a unique id by implementing the PassivationCapable interface.
> 18:52:30.858 [main] INFO  org.jboss.weld.environment.servletWeldServlet - WELD-ENV-001007: Initialize Weld using ServletContextListener
> 18:52:30.859 [main] INFO  org.jboss.weld.environment.servletWeldServlet - WELD-ENV-001002: Container detection skipped - custom container class loaded: ws.ament.hammock.bootstrap.weld3.HammockContainer.
> 18:52:31.068 [main] INFO  org.xnio - XNIO version 3.3.8.Final
> 18:52:31.083 [main] INFO  org.xnio.nio - XNIO NIO Implementation Version 3.3.8.Final
> 18:52:31.394 [main] INFO  org.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereHandler org.apache.cxf.transport.sse.atmosphere.AtmosphereSseServletDestination$DestinationHandler mapped to context-path: /
> 18:52:31.395 [main] INFO  org.atmosphere.cpr.AtmosphereFramework - Installed the following AtmosphereInterceptor mapped to AtmosphereHandler org.apache.cxf.transport.sse.atmosphere.AtmosphereSseServletDestination$DestinationHandler
> 18:52:31.434 [main] INFO  org.atmosphere.cpr.AtmosphereFramework - Atmosphere is using org.atmosphere.cpr.DefaultAnnotationProcessor for processing annotation
> 18:52:31.435 [main] INFO  org.atmosphere.cpr.DefaultAnnotationProcessor - AnnotationProcessor class org.atmosphere.cpr.DefaultAnnotationProcessor$BytecodeBasedAnnotationProcessor being used
> 18:52:33.184 [main] INFO  org.atmosphere.cpr.AtmosphereFramework - Installed WebSocketProtocol org.atmosphere.websocket.protocol.SimpleHttpProtocol 
> 18:52:33.189 [main] WARN  org.atmosphere.cpr.DefaultAsyncSupportResolver - Failed to create AsyncSupport class: class org.atmosphere.container.JSR356AsyncSupport, error: java.lang.reflect.InvocationTargetException
> 18:52:33.189 [main] ERROR org.atmosphere.cpr.DefaultAsyncSupportResolver - Real error: Unable to configure jsr356 at that stage. ServerContainer is null
> java.lang.IllegalStateException: Unable to configure jsr356 at that stage. ServerContainer is null
> 	at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:51) ~[atmosphere-runtime-2.4.14.jar:2.4.14]
> 	at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:40) ~[atmosphere-runtime-2.4.14.jar:2.4.14]
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_131]
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_131]
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_131]
> 	at org.atmosphere.cpr.DefaultAsyncSupportResolver.newCometSupport(DefaultAsyncSupportResolver.java:237) [atmosphere-runtime-2.4.14.jar:2.4.14]
> 	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolveWebSocket(DefaultAsyncSupportResolver.java:308) [atmosphere-runtime-2.4.14.jar:2.4.14]
> 	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolve(DefaultAsyncSupportResolver.java:294) [atmosphere-runtime-2.4.14.jar:2.4.14]
> 	at org.atmosphere.cpr.AtmosphereFramework.autoDetectContainer(AtmosphereFramework.java:2083) [atmosphere-runtime-2.4.14.jar:2.4.14]
> 	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:914) [atmosphere-runtime-2.4.14.jar:2.4.14]
> 	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:825) [atmosphere-runtime-2.4.14.jar:2.4.14]
> 	at org.apache.cxf.transport.sse.atmosphere.AtmosphereSseServletDestination.<init>(AtmosphereSseServletDestination.java:76) [cxf-rt-rs-sse-3.2.0.jar:3.2.0]
> 	at org.apache.cxf.transport.sse.SseHttpTransportFactory.getDestination(SseHttpTransportFactory.java:55) [cxf-rt-rs-sse-3.2.0.jar:3.2.0]
> 	at org.apache.cxf.endpoint.ServerImpl.initDestination(ServerImpl.java:84) [cxf-core-3.2.0.jar:3.2.0]
> 	at org.apache.cxf.endpoint.ServerImpl.<init>(ServerImpl.java:63) [cxf-core-3.2.0.jar:3.2.0]
> 	at org.apache.cxf.jaxrs.JAXRSServerFactoryBean.create(JAXRSServerFactoryBean.java:173) [cxf-rt-frontend-jaxrs-3.2.0.jar:3.2.0]
> 	at org.apache.cxf.jaxrs.JAXRSServerFactoryBean.init(JAXRSServerFactoryBean.java:143) [cxf-rt-frontend-jaxrs-3.2.0.jar:3.2.0]
> 	at org.apache.cxf.cdi.JAXRSCdiResourceExtension.load(JAXRSCdiResourceExtension.java:157) [cxf-integration-cdi-3.2.0.jar:3.2.0]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
> 	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95) [weld-core-impl-3.0.1.Final.jar:3.0.1.Final]
> 	at org.jboss.weld.injection.MethodInvocationStrategy$SpecialParamPlusBeanManagerStrategy.invoke(MethodInvocationStrategy.java:144) [weld-core-impl-3.0.1.Final.jar:3.0.1.Final]
> 	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330) [weld-core-impl-3.0.1.Final.jar:3.0.1.Final]
> 	at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:123) [weld-core-impl-3.0.1.Final.jar:3.0.1.Final]
> 	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308) [weld-core-impl-3.0.1.Final.jar:3.0.1.Final]
> 	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286) [weld-core-impl-3.0.1.Final.jar:3.0.1.Final]
> 	at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124) [cdi-api-2.0.jar:${parsedVersion.osgiVersion}]
> 	at org.jboss.weld.util.Observers.notify(Observers.java:166) [weld-core-impl-3.0.1.Final.jar:3.0.1.Final]
> 	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285) [weld-core-impl-3.0.1.Final.jar:3.0.1.Final]
> 	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273) [weld-core-impl-3.0.1.Final.jar:3.0.1.Final]
> 	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177) [weld-core-impl-3.0.1.Final.jar:3.0.1.Final]
> 	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:171) [weld-core-impl-3.0.1.Final.jar:3.0.1.Final]
> 	at org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java:53) [weld-core-impl-3.0.1.Final.jar:3.0.1.Final]
> 	at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:35) [weld-core-impl-3.0.1.Final.jar:3.0.1.Final]
> 	at org.jboss.weld.bootstrap.events.AfterDeploymentValidationImpl.fire(AfterDeploymentValidationImpl.java:28) [weld-core-impl-3.0.1.Final.jar:3.0.1.Final]
> 	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:489) [weld-core-impl-3.0.1.Final.jar:3.0.1.Final]
> 	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:90) [weld-core-impl-3.0.1.Final.jar:3.0.1.Final]
> 	at org.jboss.weld.environment.se.Weld.initialize(Weld.java:790) [weld-se-core-3.0.1.Final.jar:3.0.1.Final]
> 	at org.jboss.weld.environment.se.Weld.initialize(Weld.java:175) [weld-se-core-3.0.1.Final.jar:3.0.1.Final]
> 	at ws.ament.hammock.bootstrap.weld3.Weld3Bootstrapper.start(Weld3Bootstrapper.java:44) [bootstrap-weld3-2.0.jar:?]
> 	at ws.ament.hammock.Bootstrap.main(Bootstrap.java:41) [hammock-core-2.0.jar:?]
> 18:52:33.194 [main] INFO  org.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereInterceptor SSE Interceptor Support with priority AFTER_DEFAULT 
> 18:52:33.194 [main] INFO  org.atmosphere.cpr.AtmosphereFramework - Using EndpointMapper class org.atmosphere.util.DefaultEndpointMapper
> 18:52:33.194 [main] INFO  org.atmosphere.cpr.AtmosphereFramework - Using BroadcasterCache: org.atmosphere.cache.UUIDBroadcasterCache
> 18:52:33.194 [main] INFO  org.atmosphere.cpr.AtmosphereFramework - Default Broadcaster Class: org.atmosphere.cpr.DefaultBroadcaster
> 18:52:33.195 [main] INFO  org.atmosphere.cpr.AtmosphereFramework - Broadcaster Shared List Resources: false
> 18:52:33.195 [main] INFO  org.atmosphere.cpr.AtmosphereFramework - Broadcaster Polling Wait Time 100
> 18:52:33.195 [main] INFO  org.atmosphere.cpr.AtmosphereFramework - Shared ExecutorService supported: true
> 18:52:33.195 [main] INFO  org.atmosphere.cpr.AtmosphereFramework - Messaging Thread Pool Size: 20
> 18:52:33.195 [main] INFO  org.atmosphere.cpr.AtmosphereFramework - Async I/O Thread Pool Size: 20
> 18:52:33.195 [main] INFO  org.atmosphere.cpr.AtmosphereFramework - Using BroadcasterFactory: org.atmosphere.cpr.DefaultBroadcasterFactory
> 18:52:33.195 [main] INFO  org.atmosphere.cpr.AtmosphereFramework - Using AtmosphereResurceFactory: org.atmosphere.cpr.DefaultAtmosphereResourceFactory
> 18:52:33.195 [main] INFO  org.atmosphere.cpr.AtmosphereFramework - Using WebSocketProcessor: org.atmosphere.websocket.DefaultWebSocketProcessor
> 18:52:33.198 [main] INFO  org.atmosphere.cpr.AtmosphereFramework - Invoke AtmosphereInterceptor on WebSocket message true
> 18:52:33.198 [main] INFO  org.atmosphere.cpr.AtmosphereFramework - HttpSession supported: false
> 18:52:33.198 [main] INFO  org.atmosphere.cpr.AtmosphereFramework - Atmosphere is using org.atmosphere.inject.InjectableObjectFactory for dependency injection and object creation
> 18:52:33.198 [main] INFO  org.atmosphere.cpr.AtmosphereFramework - Atmosphere is using async support: org.atmosphere.container.Servlet30CometSupport running under container: Undefined/0.0 using javax.servlet/3.0
> 18:52:33.199 [main] INFO  org.atmosphere.cpr.AtmosphereFramework - Atmosphere Framework 2.4.14 started.
> 18:52:33.199 [main] INFO  org.atmosphere.cpr.AtmosphereFramework - 
> 
> 	For Atmosphere Framework Commercial Support, visit 
> 	http://www.async-io.org/ or send an email to support@async-io.org
> 
> janv. 30, 2018 6:52:33 PM org.apache.cxf.endpoint.ServerImpl initDestination
> INFOS: Setting the server's publish address to be /
> 18:52:33.271 [main] INFO  org.jboss.weld.Bootstrap - WELD-ENV-002003: Weld SE container 0a01c4da-9d7d-4a03-942b-522160b4bab6 initialized
> 18:52:33.272 [main] INFO  ws.ament.hammock.HammockRuntime - Starting webserver on http://MacLane.durand-blazart.fr:8080
> 18:52:33.406 [Thread-1] INFO  org.atmosphere.cpr.AtmosphereFramework - Latest version of Atmosphere's JavaScript Client 2.3.5
> 18:52:33.406 [Thread-1] INFO  org.atmosphere.cpr.AtmosphereFramework - 
> 
> 	Atmosphere Framework Updates:
> 	Major Update available (new features): 2.4.19

**Comment by johnament** [comment]
Can you retry this on Hammock 2.1?
