### ISSUE TITLE
Error running simple example from getting-started page

### ISSUE THREAD

**Issue by garyhodgson** [hammock-project/hammock#126]
FYI, when I [recreated ](https://gist.github.com/garyhodgson/cdf315177985b01ea4839c3a599ca0aa) the example from https://hammock-project.github.io/guides/gettingstarted.html I get the following error:

    Feb 08, 2018 8:36:32 PM org.apache.cxf.transport.servlet.ServletController invoke
    WARNING: Can't find the request for http://localhost:8080/hello's Observer

and the browser output is `No service was found.`

**Comment by garyhodgson** [comment]
Replacing the capsule build plugin with the shade plugin works however. cxf/bus-extensions problem with capsule perhaps?

**Comment by johnament** [comment]
Yes, there's a regression issue with 2.0 when using the name CDI-SE mode.  It's fixed in 2.1, hopefully coming out in a few days.

The workaround is to use a custom main method (assuming you're on Weld) and disable archive isolation.  You can see an example https://github.com/hammock-project/hammock/blob/master/bootstrap-weld3/src/main/java/ws/ament/hammock/bootstrap/weld3/Weld3Bootstrapper.java#L49-L58

Thanks for the bug report @garyhodgson !  Sorry for the delayed response.

**Comment by fiorenzino** [comment]
some news about 2.1? have you an example about The workaround use? i tried, but without success.

**Comment by johnament** [comment]
I just finished running the release steps.  Release notes and the artifacts should be coming to maven central shortly @fiorenzino

**Comment by fiorenzino** [comment]
@johnament i tried also with latest realease, but without success. No errors, but no response from a simple rest service.
Can you give us  a simple example using microprofile that works?

**Comment by johnament** [comment]
@fiorenzino Just wondering, do you have SSE turned off?  Also, make sure you have a `META-INF/beans.xml` file with some basic setup.  There's a few examples, I'm going to push up the update to point them to 2.1.

**Comment by fiorenzino** [comment]
i found in your repositories: 
https://github.com/hammock-project/microprofile-hol-1x
and your example (solution/authors) works fine.
I will replicate your project structure.

**the size of project is very impressive**:
**13M**  5 Mar 16:56 authors-capsule.jar
wow!

See you soon
fiorenzo

**Comment by johnament** [comment]
Can we consider this one closed then @garyhodgson @fiorenzino ?

**Comment by garyhodgson** [comment]
Hi John,  Sorry, I hadn't noticed the 2.1 release.  I tested and can confirm the 2.1 release works.  As an aside, the getting started page still refers to 2.0 in the pom.xml snippet.
Cheers,
