### ISSUE TITLE
Add rest-cxf-swagger artifact

### ISSUE THREAD

**Issue by immetoo** [hammock-project/hammock#131]
Like documented in the _swagger_ artifacts, cxf manages this itself with an artifact.
Only this cxf dep needs to be equal to the version in _rest-cxf_.

So an rest-cxf-swagger artifact which argegates _rest-cxf_ and the _cxf-rt-rs-service-description-swagger_ would be nice.

**Comment by johnament** [comment]
I'm not sure I see a benefit to doing this over the existing util-swagger module in Hammock (which is openapi v3.0.1 now).  What features were you looking for from the CXF specific integration?

**Comment by immetoo** [comment]
Ah yes, i assumed the _swagger_ artifact did not work on cxf.
As the swagger/readme.md says not to use it for cxf.
And the hammock-cqrs example uses this seperate _cxf-rt-rs-service-description-swagger_ artifact.

So then its just outdated documentation. (and util-swagger is not there yet)

**Comment by johnament** [comment]
Yes, sorry, that readme is out of date (had forgotten it was there).  Do you in fact see it working?

**Comment by immetoo** [comment]
Yes, it needs the following steps to work;
- add hammock _swagger_ artifact
- add annotions like @OpenAPIDefinition and @Operation
- add "/openapi-configuration.json" to classpath resources;
```
{
    "resourcePackages": [
        "com.example.project"
    ]
}
```
- optional fix "class scanning per request" ;
```
	static {
		try {
			System.out.println("Manual monkey patch OpenApiContextLocator to fix ctxId mismatch somewhere.");
			OpenApiContextLocator loc = OpenApiContextLocator.getInstance();
			Field field = OpenApiContextLocator.class.getDeclaredField("map");
			field.setAccessible(true);
			field.set(loc, new ConcurrentMapSingleKey());
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	public static class ConcurrentMapSingleKey extends ConcurrentHashMap<String, OpenApiContext> {
		private static final String SINGLE_KEY = ConcurrentMapSingleKey.class.getSimpleName();
		@Override
		public OpenApiContext get(Object key) { return super.get(SINGLE_KEY); }
		@Override
		public OpenApiContext put(String key, OpenApiContext value) { return super.put(SINGLE_KEY, value); }
	}
```
Maybe bug in rc4 or i missed how to config that correctly :)
