### ISSUE TITLE
CXFProvider can't start without sse impl classes.

### ISSUE THREAD

**Issue by immetoo** [hammock-project/hammock#132]
When using;
cxf.enable.sse.transport=false

and removing deps by excluding the _cxf-rt-rs-sse_ artifact.

We get NoClassDefFoundError in the CXFProvider class on;
import org.apache.cxf.jaxrs.sse.SseFeature;
import org.apache.cxf.transport.sse.SseHttpTransportFactory;

It would be nice if users can use cxf without an/that sse implemention on classpath.

**Comment by johnament** [comment]
@immetoo yes, agreed.  however, there's some problems within CXF.  Finally they are fixed for the CXF 3.2.3 release, hopefully we will release that then switch over
