### ISSUE TITLE
Add @DataSourceDefinition support

### ISSUE THREAD

**Issue by antoinesd** [hammock-project/hammock#24]
For a better user experience with JPA and future database related feature, we should add a module allowing definition and thus automatic creation of a datasource.
Information would be read thru a CDI extension in a `ProcessAnnotatedType` observer.

To make this module useful we need a JNDI module (datasources are looked thru JNDI in JPA) and make sure that if we add eager instantiation of Persistence Units, it will be done after (probably in an AfterBeanDiscovery event)

**Comment by antoinesd** [comment]
This depends on #25

**Comment by johnament** [comment]
Why does this depend on JNDI?  We should be able to define datasources without necessarily binding them in JNDI, we can provide standard CDI beans for those datasources.

**Comment by johnament** [comment]
@antoinesd based on what we spoke about.. good?
