### ISSUE TITLE
beans.xml missing

### ISSUE THREAD

**Issue by irimia-dragos** [hammock-project/hammock#50]
The beans.xml file is missing from the resteasy module.

For projects which will have only ws.ament.hammock:web-undertow and ws.ament.hammock:rest-resteasy the ws.ament.hammock.rest.resteasy.ResteasyServletContextAttributeProvider is not injected in weld. All requests will go though to the local files.

Add a beans.xml file in the  ws.ament.hammock:rest-resteasy project.

**Comment by johnament** [comment]
Ah good catch, thanks!  I don't suppose you'd be interested in raising a PR for this? Otherwise I can add.
