### ISSUE TITLE
path property from ApplicationPath ignored

### ISSUE THREAD

**Issue by irimia-dragos** [hammock-project/hammock#55]
It seems that the ApplicationPath annotation value is ignored (from the rest Application class).

For example, the test `ws.ament.hammock.rest.resteasy.ResteasyTest` still passes, even if you change the class `ws.ament.hammock.rest.resteasy.RestApp` like this:
`
@ApplicationPath("/testme")
@ApplicationScoped
public class RestApp extends Application{
}
`

Expected result:
The path should be /testme/rest but instead is till /rest.

**Comment by johnament** [comment]
This is similar to #18 .

The problem specific to resteasy, the way it operates it actually is creating multiple bindings.  You may want to check w/ cxf as well.
