### ISSUE TITLE
Question: Start Application without Packaging

### ISSUE THREAD

**Issue by fsomme2s** [hammock-project/hammock#72]
Hi,

when I run _maven package shade_ and _then manually start the app_ with java- jar ..., everything works fine.

When I try to simply run the Bootstrap class from within my IDE, the server starts and it is using my hammock.properties file in the resources directroy, **but it is not finding any of my Jax-RS endpoints.** I can't get any HTTP response from the server.

Am I doing sth. wrong or is it just not possible to run the app without packaging...?

**Comment by johnament** [comment]
It should be able to find your JAX-RS resources without any issues.  Are they in your main project or in a dependency?

**Comment by fsomme2s** [comment]
They are in my main project...

**Comment by johnament** [comment]
Ok, and just to confirm, you have a beans.xml file in the proper location (for CDI)?  Can you share some of your project structure

**Comment by fsomme2s** [comment]
I started IntelliJ, create new maven project,
add dependencies for web-undertow, rest-resteasy, boostrap-weld - hammock.version 1.1

then added hammock.properties with port=4711
then added a requestscoped @Path("/status") with an @GET, returning "up and running"

Then: IntelliJ Run-Config: Main class = ws.ament.hammock.Bootstrap

so my structure is:
pom.xml
src/main/java/.../StatusAPI
src/main/resources/hammock.properties

Added .../META-INF/beans.xml but did not work either

As I said, when I package the uber-jar and run it with java -jar, it works fine.

Sorry for my slow response time ;)

**Comment by fsomme2s** [comment]
Oh snap!
I am sorry, it actually is running. The log output says "Starting webserver on http://0.0.0.0:4711" - i did not read the ip and just clicked on the link, leading to no response. When I visit localhost:4711 it works.

Strange, though, that it logs the wrong IP.

**Comment by johnament** [comment]
Ok, great that explains it.  I'll convert this to an enhancement to fix the output IP address when bind address = 0.0.0.0.
